### ISSUE TITLE
npm run compile returns build error

### ISSUE THREAD

**Issue by jwoehr** [Baxi-codes/OpenQASM-LSP#1]
```
(qdev_env) jwoehr@pop-os:~/work/Qiskit/OpenQASM/OpenQASM-LSP$ npm run compile

> lsp-sample@1.0.0 compile
> tsc -b

server/src/server.ts:24:38 - error TS2307: Cannot find module '../../grammar/out/qasm3Error' or its corresponding type declarations.

24 import { getParserDiagnostics } from '../../grammar/out/qasm3Error';
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.
```

**Comment by Baxi-codes** [comment]
Sorry for the issues, I don't have much experience in publishing code and there are a lot of errors in the source (it doesn't work the same when downloaded). I will try to fix it soon :(

**Comment by jwoehr** [comment]
What you are doing is excellent, looking forward to seeing your OpenQASM 3 LSP progress.

**Comment by Baxi-codes** [comment]
The issue is fixed, I changed the compilation order so that the grammar part is compiled first. Sorry for taking so long, I was being a bit lazy :sweat_smile:.
