### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jwoehr** [Baxi-codes/OpenQASM-LSP#2]
Hi @Baxi-codes  --- are you still interested in this project?
I was thinking of forking and trying to continue it.
However, you have no open source license attached.
Would you rather I made contributions and issued Pull Requests to your project?
Thank you.

**Comment by jwoehr** [comment]
I find that I already forked this project last year!
I will update my fork.
Hoping to hear from you about your plans.

**Comment by Baxi-codes** [comment]
I can't add any licenses right now, the project has modified and unmodified version of files from microsoft's lsp examples including the comments:
```
/* --------------------------------------------------------------------------------------------
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 * ------------------------------------------------------------------------------------------ */
 ```

I just started this project for a term assignment. If you wish to use it, then I guess I will have to do something about these. Do you have any ideas on how should I go about solving this?

**Comment by jwoehr** [comment]
You just add your license to your own works. If you read the MIT license it allows you to redistribute and modify. So you ignore those and merely provide an MIT or BSD-3 or Apache license or whatever to your own work.

BTW I'm trying to update the openqasm3 grammar in my own fork. Some code throws errors and the error listener is not inheriting from the Antlr4 ErrorListener so it reports `TypeError: o.reportAttemptingFullContext is not a function`

This sort of thing is noted in https://github.com/antlr/antlr4/issues/2623

**Comment by jwoehr** [comment]
I really admire your work here. You did a great job. I'm just trying to update it a bit.

**Comment by Baxi-codes** [comment]
I have added the MIT license. Feel free to work on your fork or add PRs! I might push some code in the future if I feel like it.
